version: 0.2
phases:
  install:
    commands:
      - echo Executing Install phase
      - which python
      - pip install pyyaml
      - apt-get install python-yaml
      - which python
      - python --version
      - lsb_release -a
      - uname -r
      - apt-get update
      - pip install --upgrade pip
      - pip install redis
      - ls -a
      
      - locate setup.py 

    finally:
      - echo Executing INSTALL FINALLY
  pre_build:
    commands:
      - echo Executing pre build phase
    finally:
      - echo Executing PRE BUILD FINALLY
  build:
    commands:
      - echo Executing build phase
    finally:
      - echo Executing BUILD FINALLY

  post_build:
    commands:
      - echo Executing post build phase


