version: 0.2
phases:
  install:
    commands:
      - echo Executing Install phase
      - pip install pyyaml
      - apt-get install python-yaml
      - which python
      - python --version
    finally:
      - echo Executing INSTALL FINALLY
  pre_build:
    commands:
      - echo Executing pre build phase
    finally:
      - echo Executing PRE BUILD FINALLY
  build:
    commands:
      - echo Executing build phase
    finally:
      - echo Executing BUILD FINALLY

  post_build:
    commands:
      - echo Executing post build phase


