version: 0.2
phases:
  install:
    commands:
      - echo Executing Install phase
      - which python
      - pip install pyyaml
      - apt-get install python-yaml
      - which python
      - python --version
      - lsb_release -a
      - uname -r
      - apt-get install -y redis-server  
      - redis-server -v
      - /etc/init.d/redis* start
      - apt-get install -y netstat
      - netstat -nap | grep -i 6379
      - ps -ef | grep -i redis

    finally:
      - echo Executing INSTALL FINALLY
  pre_build:
    commands:
      - echo Executing pre build phase
    finally:
      - echo Executing PRE BUILD FINALLY
  build:
    commands:
      - echo Executing build phase
    finally:
      - echo Executing BUILD FINALLY

  post_build:
    commands:
      - echo Executing post build phase


